import { LiveEvent } from '../../types';

const now = new Date();
const h = (hours: number) => new Date(now.getTime() + hours * 3600000).toISOString();

export const MOCK_EVENTS: LiveEvent[] = [
  {
    id: 'evt-001',
    festivalId: 'fest-001',
    festivalName: 'Nuit Sonore',
    festivalLogoUrl: null,
    title: 'Opening Set',
    description: 'Le set d\'ouverture de la saison. Amélie Lens nous emporte dans un voyage techno hypnotique de 2 heures, entre mélodies planantes et basses percutantes.',
    djName: 'Amélie Lens',
    coverImageUrl: null,
    scheduledStartTime: h(-1),
    scheduledEndTime: h(1),
    actualStartTime: h(-1),
    actualEndTime: null,
    status: 'live',
    cameraId: 'cam-001',
    playbackUrl: null,
    viewerCount: 847,
    createdAt: h(-48),
  },
  {
    id: 'evt-002',
    festivalId: 'fest-001',
    festivalName: 'Nuit Sonore',
    festivalLogoUrl: null,
    title: 'Techno Marathon',
    description: 'Charlotte de Witte livre un set techno intense de 3 heures. Préparez-vous pour un voyage sonore sans compromis.',
    djName: 'Charlotte de Witte',
    coverImageUrl: null,
    scheduledStartTime: h(24),
    scheduledEndTime: h(27),
    actualStartTime: null,
    actualEndTime: null,
    status: 'scheduled',
    cameraId: 'cam-001',
    playbackUrl: null,
    viewerCount: 0,
    createdAt: h(-72),
  },
  {
    id: 'evt-003',
    festivalId: 'fest-002',
    festivalName: 'Warehouse Project',
    festivalLogoUrl: null,
    title: 'Deep House Session',
    description: 'Peggy Gou transforme le Warehouse en dancefloor géant avec ses productions house colorées et énergiques.',
    djName: 'Peggy Gou',
    coverImageUrl: null,
    scheduledStartTime: h(48),
    scheduledEndTime: h(50),
    actualStartTime: null,
    actualEndTime: null,
    status: 'scheduled',
    cameraId: 'cam-003',
    playbackUrl: null,
    viewerCount: 0,
    createdAt: h(-96),
  },
  {
    id: 'evt-004',
    festivalId: 'fest-001',
    festivalName: 'Nuit Sonore',
    festivalLogoUrl: null,
    title: 'Closing Ceremony',
    description: 'Nina Kraviz clôture le festival avec un set mémorable mêlant techno, acid et électro expérimentale.',
    djName: 'Nina Kraviz',
    coverImageUrl: null,
    scheduledStartTime: h(72),
    scheduledEndTime: h(74),
    actualStartTime: null,
    actualEndTime: null,
    status: 'scheduled',
    cameraId: 'cam-002',
    playbackUrl: null,
    viewerCount: 0,
    createdAt: h(-24),
  },
  {
    id: 'evt-005',
    festivalId: 'fest-002',
    festivalName: 'Warehouse Project',
    festivalLogoUrl: null,
    title: 'Ambient Night',
    description: 'Jon Hopkins explore les territoires sonores entre ambient, IDM et techno mélodique. Une expérience immersive.',
    djName: 'Jon Hopkins',
    coverImageUrl: null,
    scheduledStartTime: h(96),
    scheduledEndTime: h(98),
    actualStartTime: null,
    actualEndTime: null,
    status: 'scheduled',
    cameraId: 'cam-003',
    playbackUrl: null,
    viewerCount: 0,
    createdAt: h(-12),
  },
  {
    id: 'evt-006',
    festivalId: 'fest-001',
    festivalName: 'Nuit Sonore',
    festivalLogoUrl: null,
    title: 'Sunrise Session',
    description: 'Boris Brejcha et son masque légendaire pour un set minimal techno au lever du soleil.',
    djName: 'Boris Brejcha',
    coverImageUrl: null,
    scheduledStartTime: h(120),
    scheduledEndTime: h(122),
    actualStartTime: null,
    actualEndTime: null,
    status: 'scheduled',
    cameraId: 'cam-001',
    playbackUrl: null,
    viewerCount: 0,
    createdAt: h(-6),
  },
  {
    id: 'evt-007',
    festivalId: 'fest-001',
    festivalName: 'Nuit Sonore',
    festivalLogoUrl: null,
    title: 'Warehouse Vibes',
    description: 'Set terminé d\'hier soir. Adam Beyer a livré une performance époustouflante.',
    djName: 'Adam Beyer',
    coverImageUrl: null,
    scheduledStartTime: h(-26),
    scheduledEndTime: h(-24),
    actualStartTime: h(-26),
    actualEndTime: h(-24),
    status: 'ended',
    cameraId: 'cam-001',
    playbackUrl: null,
    viewerCount: 1243,
    createdAt: h(-120),
  },
  {
    id: 'evt-008',
    festivalId: 'fest-002',
    festivalName: 'Warehouse Project',
    festivalLogoUrl: null,
    title: 'Bass Culture',
    description: 'Set terminé. Skrillex a enflammé la salle avec un mix dubstep et bass music.',
    djName: 'Skrillex',
    coverImageUrl: null,
    scheduledStartTime: h(-50),
    scheduledEndTime: h(-48),
    actualStartTime: h(-50),
    actualEndTime: h(-48),
    status: 'ended',
    cameraId: 'cam-003',
    playbackUrl: null,
    viewerCount: 2156,
    createdAt: h(-168),
  },
];
